function ReportCard({ report }) {


  if (!report) {

    return null;

  }



  return (


    <div className="bg-zinc-900 border border-zinc-800 rounded-2xl p-6">



      {/* Header */}

      <div className="flex justify-between items-start mb-6">


        <div>


          <h2 className="text-lg font-semibold">

            Investigation Report

          </h2>


          <p className="text-sm text-gray-400 mt-1">

            Generated by TraceLens analysis agents

          </p>


        </div>




        <span className="text-xs bg-blue-500/10 border border-blue-500/30 text-blue-400 px-3 py-1 rounded-full">

          AI Generated

        </span>


      </div>







      {/* Metrics */}


      <div className="grid md:grid-cols-2 gap-4">



        <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-5">


          <p className="text-xs text-gray-400">

            Risk Level

          </p>


          <p className={`text-2xl font-semibold mt-2

          ${
            report.risk === "High"

            ? "text-red-400"

            : report.risk === "Medium"

            ? "text-yellow-400"

            : "text-green-400"

          }

          `}>

            {report.risk}

          </p>


        </div>






        <div className="bg-zinc-950 border border-zinc-800 rounded-xl p-5">


          <p className="text-xs text-gray-400">

            Confidence Score

          </p>


          <p className="text-2xl font-semibold text-green-400 mt-2">

            {report.confidence}%

          </p>


          <div className="mt-3 h-2 bg-zinc-800 rounded-full overflow-hidden">


            <div

              className="h-full bg-green-500"

              style={{

                width:`${report.confidence}%`

              }}

            />


          </div>


        </div>



      </div>









      {/* Summary */}


      <div className="mt-8">


        <h3 className="text-sm font-medium text-gray-200">

          Summary

        </h3>



        <div className="mt-3 bg-zinc-950 border border-zinc-800 rounded-xl p-4">


          <p className="text-sm text-gray-300 leading-relaxed">

            {report.summary}

          </p>


        </div>


      </div>









      {/* Findings */}


      <div className="mt-8">


        <h3 className="text-sm font-medium text-gray-200">

          Key Findings

        </h3>



        <div className="mt-3 space-y-3">


        {

          report.findings?.map((finding,index)=>(


            <div

              key={index}

              className="flex gap-3 items-center bg-zinc-950 border border-zinc-800 rounded-xl p-4"

            >


              <span className="text-blue-400">

                ✓

              </span>



              <span className="text-sm text-gray-300">

                {finding}

              </span>


            </div>


          ))

        }


        </div>


      </div>





    </div>


  );

}


export default ReportCard;