import Card from "./ui/Card";
import Badge from "./ui/Badge";


function ReportCard({report}){


if(!report){
return null;
}


const riskType =
report.risk === "High"
? "danger"
:
report.risk === "Medium"
? "warning"
:
"success";



return (

<Card>

<div className="space-y-8">


{/* HEADER */}

<div className="
flex
justify-between
items-start
">

<div>

<h2 className="
text-2xl
font-bold
">

Investigation Report

</h2>

<p className="
text-sm
text-gray-400
mt-2
">

Generated by TraceLens AI agents

</p>

</div>


<Badge type="info">
AI Generated
</Badge>


</div>





{/* METRICS */}

<div className="
grid
md:grid-cols-2
gap-6
">


<div className="
bg-[#101a30]
rounded-2xl
p-6
border
border-white/5
">

<p className="
text-sm
text-gray-400
">

Risk Assessment

</p>


<div className="mt-4">

<Badge type={riskType}>

{report.risk || "Unknown"}

</Badge>

</div>


</div>






<div className="
bg-[#101a30]
rounded-2xl
p-6
border
border-white/5
">


<div className="
flex
justify-between
">

<p className="
text-sm
text-gray-400
">

Confidence Score

</p>


<span className="
text-green-400
font-bold
">

{report.confidence || 0}%

</span>


</div>



<div className="
mt-5
h-3
bg-black/40
rounded-full
overflow-hidden
">


<div

className="
h-full
bg-green-400
rounded-full
"

style={{
width:`${report.confidence || 0}%`
}}

/>


</div>


</div>



</div>







{/* SUMMARY */}

<div>


<h3 className="
text-lg
font-semibold
mb-3
">

AI Summary

</h3>


<div className="
bg-[#101a30]
rounded-2xl
p-6
text-gray-300
leading-relaxed
border
border-white/5
">

{report.summary || "No summary generated."}


</div>


</div>








{/* FINDINGS */}

<div>


<h3 className="
text-lg
font-semibold
mb-4
">

Key Findings

</h3>



<div className="
space-y-4
">


{

report.findings?.length ?


report.findings.map((item,index)=>(


<div

key={index}

className="
flex
gap-4
items-start
bg-[#101a30]
rounded-2xl
p-5
border
border-white/5
"


>


<div className="
min-w-8
h-8
rounded-full
bg-green-500/20
text-green-400
flex
items-center
justify-center
font-bold
">

✓

</div>


<p className="
text-gray-300
text-sm
leading-relaxed
">

{item}

</p>


</div>


))


:


<p className="text-gray-500">

No findings available

</p>


}


</div>


</div>



</div>


</Card>

);


}


export default ReportCard;