function ReportCard({ report }) {


  if (!report) {

    return null;

  }



  return (

    <div className="mt-10 bg-gray-900 border border-gray-800 rounded-2xl p-6 shadow-xl">



      <div className="flex items-center justify-between mb-6">


        <h2 className="text-2xl font-bold">

          AI Investigation Report

        </h2>


        <span className="text-sm bg-gray-800 px-3 py-1 rounded-full text-gray-400">

          Generated by TraceLens AI

        </span>


      </div>







      <div className="grid md:grid-cols-2 gap-5">



        <div className="bg-gray-800 rounded-xl p-5 border border-gray-700">


          <p className="text-gray-400">

            Risk Level

          </p>


          <p className="text-yellow-400 text-3xl font-bold mt-2">

            {report.risk}

          </p>


        </div>





        <div className="bg-gray-800 rounded-xl p-5 border border-gray-700">


          <p className="text-gray-400">

            Confidence Score

          </p>


          <p className="text-green-400 text-3xl font-bold mt-2">

            {report.confidence}%

          </p>


        </div>



      </div>









      <div className="mt-8">


        <h3 className="text-xl font-semibold">

          Investigation Summary

        </h3>



        <div className="mt-3 bg-gray-800 rounded-xl p-5 border border-gray-700">


          <p className="text-gray-300 leading-relaxed">

            {report.summary}

          </p>


        </div>


      </div>









      <div className="mt-8">


        <h3 className="text-xl font-semibold">

          Key Findings

        </h3>



        <div className="mt-4 space-y-3">



          {

            report.findings?.map((finding, index) => (


              <div

                key={index}

                className="flex items-center gap-4 bg-gray-800 border border-gray-700 p-4 rounded-xl"

              >



                <span className="text-green-400 text-2xl font-bold">

                  ✔

                </span>




                <span className="text-gray-200">

                  {finding}

                </span>



              </div>


            ))

          }



        </div>


      </div>





    </div>

  );

}



export default ReportCard;